spring:
  datasource:
    hikari:
      #最大连接数，默认是 10
      maximum-pool-size: 30
      #最小空闲连接数
      minimum-idle: 10
      #连接的超时时间，默认30000 (毫秒)
      connection-timeout: 60000
      #空闲连接最大存活时间（毫秒）
      idle-timeout: 60000
      #池中连接的最长生命周期，值 0 表示无限生命周期（毫秒）
      max-lifetime: 600000
      #连接到数据库时等待最长时间(秒)
      login-timeout: 5
  profiles:
    active: "dev"
blog:
  jwt:
    expire: 604800
    header: "Authorization"